spring:
  servlet:
    multipart:
      max-file-size:
        20MB
      max-request-size:
        20MB
  config:
    import: optional:credential.yml,aws.yml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
