spring:
  servlet:
    multipart:
      max-file-size:
        20MB
      max-request-size:
        20MB
  config:
    import: optional:credential.yml,aws.yml,mail.yml,env.yml

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
